module.exports = { BACKEND_SERVER_PORT: 4000 };
export const FETCH_REPORTS = "FETCH_REPORTS";
export const FETCH_NEXT_SUBSET_OF_REPORTS = "FETCH_NEXT_SUBSET_OF_REPORTS";
export const ARCHIVE_REPORT = "ARCHIVE_REPORT";
